version: "3"
services:
    mongo-2-2:
        container_name: "mongo-2-2"
        image: mongo:4.0.1
        ports:
            - "30022:27017"
        command: mongod --replSet rs2 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
        restart: always
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/rs2/node2/db:/data/db
            # 数据节点不需要配置文件
            # - ./data/rs2/node2/configdb:/data/configdb

    mongo-2-3:
        container_name: "mongo-2-3"
        image: mongo:4.0.1
        ports:
            - "30023:27017"
        command: mongod --replSet rs2 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
        restart: always
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/rs2/node3/db:/data/db
            # 数据节点不需要配置文件
            # - ./data/rs2/node3/configdb:/data/configdb

    mongo-2-1:
        container_name: "mongo-2-1"
        image: mongo:4.0.1
        ports:
            - "30021:27017"
        command: mongod --replSet rs2 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-2-2:mongo-2-2
            - mongo-2-3:mongo-2-3
        restart: always
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/rs2/node1/db:/data/db
            # 数据节点不需要配置文件
            # - ./data/rs2/node1/configdb:/data/configdb

    mongo-rs2-setup:
        container_name: "mongo-rs2-setup"
        image: mongo:4.0.1
        depends_on:
            - "mongo-2-1"
            - "mongo-2-2"
            - "mongo-2-3"
        links:
            - mongo-2-1:mongo-2-1
            - mongo-2-2:mongo-2-2
            - mongo-2-3:mongo-2-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-2-1
            - MONGO2=mongo-2-2
            - MONGO3=mongo-2-3
            - RS=rs2
        entrypoint: ["/scripts/setup.sh"]
